from dataclasses import dataclass


ENTITY_TYPES = (
    "document",
    "drawing_set",
    "drawing_sheet",
    "drawing_revision",
    "drawing_issue",
    "rfi",
    "submittal",
    "punch_item",
    "change_order",
    "daily_log",
)


@dataclass(frozen=True)
class RelationshipDefinition:
    label: str
    reverse_label: str
    symmetric: bool = False


RELATIONSHIP_DEFINITIONS = {
    "references": RelationshipDefinition("References", "Referenced by"),
    "responds_to": RelationshipDefinition("Responds to", "Has response"),
    "supersedes": RelationshipDefinition("Supersedes", "Superseded by"),
    "supports": RelationshipDefinition("Supports", "Supported by"),
    "impacts": RelationshipDefinition("Impacts", "Impacted by"),
    "originated_from": RelationshipDefinition(
        "Originated from",
        "Origin of",
    ),
    "resolves": RelationshipDefinition("Resolves", "Resolved by"),
    "documents": RelationshipDefinition("Documents", "Documented by"),
    "includes": RelationshipDefinition("Includes", "Included in"),
    "associated_with": RelationshipDefinition(
        "Associated with",
        "Associated with",
        symmetric=True,
    ),
    "located_on": RelationshipDefinition("Located on", "Contains"),
    "generated_by": RelationshipDefinition("Generated by", "Generated"),
}

SYMMETRIC_RELATIONSHIP_TYPES = frozenset(
    relationship_type
    for relationship_type, definition in RELATIONSHIP_DEFINITIONS.items()
    if definition.symmetric
)

# Specialized drawing issue membership, document version lineage, drawing
# revision supersession, and folder containment remain outside this matrix.
ALLOWED_RELATIONSHIPS = frozenset(
    {
        ("rfi", "references", "drawing_sheet"),
        ("rfi", "references", "drawing_revision"),
        ("rfi", "responds_to", "drawing_revision"),
        ("rfi", "originated_from", "submittal"),
        ("rfi", "impacts", "change_order"),
        ("submittal", "references", "drawing_sheet"),
        ("submittal", "references", "drawing_revision"),
        ("submittal", "responds_to", "rfi"),
        ("submittal", "impacts", "change_order"),
        ("punch_item", "located_on", "drawing_sheet"),
        ("punch_item", "located_on", "drawing_revision"),
        ("punch_item", "impacts", "change_order"),
        ("punch_item", "resolves", "rfi"),
        ("change_order", "originated_from", "rfi"),
        ("change_order", "originated_from", "submittal"),
        ("change_order", "originated_from", "punch_item"),
        ("change_order", "references", "drawing_revision"),
        ("change_order", "impacts", "drawing_sheet"),
        ("change_order", "resolves", "rfi"),
        ("daily_log", "documents", "rfi"),
        ("daily_log", "documents", "submittal"),
        ("daily_log", "documents", "punch_item"),
        ("daily_log", "documents", "change_order"),
        ("daily_log", "references", "drawing_revision"),
        ("document", "supports", "rfi"),
        ("document", "supports", "submittal"),
        ("document", "supports", "change_order"),
        ("drawing_issue", "includes", "document"),
        ("document", "associated_with", "drawing_set"),
        ("document", "associated_with", "drawing_sheet"),
        ("document", "associated_with", "drawing_revision"),
        ("document", "associated_with", "drawing_issue"),
        ("document", "associated_with", "rfi"),
        ("document", "associated_with", "submittal"),
        ("document", "associated_with", "punch_item"),
        ("document", "associated_with", "change_order"),
        ("document", "associated_with", "daily_log"),
    }
)


def is_symmetric_relationship(relationship_type: str) -> bool:
    return relationship_type in SYMMETRIC_RELATIONSHIP_TYPES


def is_allowed_relationship(
    source_type: str,
    relationship_type: str,
    target_type: str,
) -> bool:
    relationship = (source_type, relationship_type, target_type)
    if relationship in ALLOWED_RELATIONSHIPS:
        return True
    if not is_symmetric_relationship(relationship_type):
        return False
    return (target_type, relationship_type, source_type) in ALLOWED_RELATIONSHIPS


def canonicalize_relationship(
    source_type: str,
    source_id: int,
    target_type: str,
    target_id: int,
    relationship_type: str,
) -> tuple[str, int, str, int]:
    source = (source_type, source_id)
    target = (target_type, target_id)
    if is_symmetric_relationship(relationship_type) and target < source:
        source, target = target, source
    return source[0], source[1], target[0], target[1]


def perspective_label(relationship_type: str, direction: str) -> str:
    definition = RELATIONSHIP_DEFINITIONS[relationship_type]
    if direction == "incoming":
        return definition.reverse_label
    return definition.label
