import { useEffect, useId, useRef, useState } from "react";

import { formatScheduleDate } from "../../utils/scheduleVariance";
import Button from "../ui/Button";
import Icon from "../ui/Icon";


function CreateBaselineDialog({
  open,
  scheduleStartDate,
  taskCount,
  isSubmitting,
  serverError,
  onSubmit,
  onCancel,
  onClearError,
}) {
  const titleId = useId();
  const descriptionId = useId();
  const errorId = useId();
  const dialogRef = useRef(null);
  const nameRef = useRef(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [validationError, setValidationError] = useState(null);

  useEffect(() => {
    if (!open) return undefined;

    const previouslyFocused = document.activeElement;
    nameRef.current?.focus();

    return () => {
      if (previouslyFocused instanceof HTMLElement) previouslyFocused.focus();
    };
  }, [open]);

  if (!open) return null;

  const error = validationError || serverError?.message || null;

  const handleKeyDown = (event) => {
    if (event.key === "Escape" && !isSubmitting) {
      event.stopPropagation();
      onCancel();
      return;
    }
    if (event.key !== "Tab") return;

    const focusable =
      dialogRef.current?.querySelectorAll(
        "input:not(:disabled), textarea:not(:disabled), button:not(:disabled)"
      ) || [];
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    const trimmedName = name.trim();
    const trimmedDescription = description.trim();

    if (!trimmedName) {
      setValidationError("Enter a baseline name.");
      nameRef.current?.focus();
      return;
    }

    const result = await onSubmit({
      name: trimmedName,
      description: trimmedDescription || null,
    });
    if (result) onCancel();
  };

  return (
    <div
      className="dialog-overlay"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget && !isSubmitting) onCancel();
      }}
    >
      <div
        ref={dialogRef}
        className="dialog schedule-baseline-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descriptionId}
        onKeyDown={handleKeyDown}
      >
        <div className="dialog__header">
          <span className="dialog__icon">
            <Icon name="calendar" size={20} />
          </span>
          <div className="dialog__text">
            <h2 id={titleId} className="dialog__title">
              Capture Schedule Baseline
            </h2>
            <p id={descriptionId} className="dialog__message">
              Preserve the current planned schedule for future variance
              comparison. Snapshot data cannot be edited after capture.
            </p>
          </div>
        </div>

        <dl className="schedule-baseline-context">
          <div>
            <dt>Schedule start</dt>
            <dd>{formatScheduleDate(scheduleStartDate)}</dd>
          </div>
          <div>
            <dt>Tasks</dt>
            <dd>{taskCount}</dd>
          </div>
          <div>
            <dt>Captured at</dt>
            <dd>Generated by the server</dd>
          </div>
        </dl>

        <form className="form-stack" noValidate onSubmit={handleSubmit}>
          <div className="field-group">
            <label className="field-label" htmlFor={`${titleId}-name`}>
              Baseline name
            </label>
            <input
              ref={nameRef}
              id={`${titleId}-name`}
              className="field-control"
              maxLength={120}
              required
              disabled={isSubmitting}
              value={name}
              aria-invalid={Boolean(error)}
              aria-describedby={error ? errorId : undefined}
              onChange={(event) => {
                setName(event.target.value);
                setValidationError(null);
                onClearError?.();
              }}
            />
          </div>
          <div className="field-group">
            <label className="field-label" htmlFor={`${titleId}-description`}>
              Description <span className="field-optional">Optional</span>
            </label>
            <textarea
              id={`${titleId}-description`}
              className="field-control"
              rows={3}
              maxLength={2000}
              disabled={isSubmitting}
              value={description}
              onChange={(event) => setDescription(event.target.value)}
            />
          </div>
          {error && (
            <p id={errorId} className="schedule-baseline-error" role="alert">
              {error}
            </p>
          )}
          <div className="dialog__actions">
            <Button disabled={isSubmitting} onClick={onCancel}>
              Cancel
            </Button>
            <Button
              type="submit"
              variant="primary"
              disabled={isSubmitting}
              aria-busy={isSubmitting}
            >
              <Icon name="calendar" size={16} />
              {isSubmitting ? "Capturing..." : "Capture Baseline"}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}


export default CreateBaselineDialog;
