import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";

import CreateBaselineDialog from "./CreateBaselineDialog";


const baseProps = {
  open: true,
  scheduleStartDate: "2026-07-01",
  taskCount: 12,
  isSubmitting: false,
  serverError: null,
  onSubmit: vi.fn(),
  onCancel: vi.fn(),
  onClearError: vi.fn(),
};


describe("CreateBaselineDialog", () => {
  it("explains immutable server capture context and validates the name", async () => {
    const user = userEvent.setup();
    const onSubmit = vi.fn();
    render(<CreateBaselineDialog {...baseProps} onSubmit={onSubmit} />);

    expect(screen.getByText(/cannot be edited after capture/i)).toBeInTheDocument();
    expect(screen.getByText("07/01/2026")).toBeInTheDocument();
    expect(screen.getByText("12")).toBeInTheDocument();
    expect(screen.getByText("Generated by the server")).toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "Capture Baseline" }));
    expect(screen.getByRole("alert")).toHaveTextContent("Enter a baseline name");
    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("trims values, prevents duplicate submission while pending, and shows server feedback", async () => {
    const user = userEvent.setup();
    const onSubmit = vi.fn().mockResolvedValue({ baseline: { id: 1 } });
    const onCancel = vi.fn();
    const { rerender } = render(
      <CreateBaselineDialog
        {...baseProps}
        onSubmit={onSubmit}
        onCancel={onCancel}
      />
    );

    await user.type(screen.getByLabelText("Baseline name"), "  Bid Set  ");
    await user.type(screen.getByLabelText(/Description/), "  Initial issue  ");
    await user.click(screen.getByRole("button", { name: "Capture Baseline" }));
    expect(onSubmit).toHaveBeenCalledWith({
      name: "Bid Set",
      description: "Initial issue",
    });
    expect(onCancel).toHaveBeenCalledOnce();

    rerender(
      <CreateBaselineDialog
        {...baseProps}
        isSubmitting
        serverError={{ message: "A baseline with this name already exists" }}
      />
    );
    expect(screen.getByRole("alert")).toHaveTextContent("already exists");
    expect(screen.getByRole("button", { name: "Capturing..." })).toBeDisabled();
  });

  it("traps focus, closes with Escape, and restores focus", async () => {
    const user = userEvent.setup();
    const onCancel = vi.fn();
    const trigger = document.createElement("button");
    document.body.appendChild(trigger);
    trigger.focus();

    const { rerender } = render(
      <CreateBaselineDialog {...baseProps} onCancel={onCancel} />
    );
    expect(screen.getByLabelText("Baseline name")).toHaveFocus();

    await user.tab({ shift: true });
    expect(screen.getByRole("button", { name: "Capture Baseline" })).toHaveFocus();
    await user.keyboard("{Escape}");
    expect(onCancel).toHaveBeenCalledOnce();

    rerender(<CreateBaselineDialog {...baseProps} open={false} onCancel={onCancel} />);
    expect(trigger).toHaveFocus();
    trigger.remove();
  });
});
