export const RELATIONSHIP_ENTITY_LABELS = {
  document: "Document",
  drawing_set: "Drawing Set",
  drawing_sheet: "Drawing Sheet",
  drawing_revision: "Drawing Revision",
  drawing_issue: "Drawing Issue",
  rfi: "RFI",
  submittal: "Submittal",
  punch_item: "Punch Item",
  change_order: "Change Order",
  daily_log: "Daily Log",
};

export const RELATIONSHIP_DEFINITIONS = {
  references: { label: "References", reverseLabel: "Referenced by" },
  responds_to: { label: "Responds to", reverseLabel: "Has response" },
  supersedes: { label: "Supersedes", reverseLabel: "Superseded by" },
  supports: { label: "Supports", reverseLabel: "Supported by" },
  impacts: { label: "Impacts", reverseLabel: "Impacted by" },
  originated_from: {
    label: "Originated from",
    reverseLabel: "Origin of",
  },
  resolves: { label: "Resolves", reverseLabel: "Resolved by" },
  documents: { label: "Documents", reverseLabel: "Documented by" },
  includes: { label: "Includes", reverseLabel: "Included in" },
  associated_with: {
    label: "Associated with",
    reverseLabel: "Associated with",
    symmetric: true,
  },
  located_on: { label: "Located on", reverseLabel: "Contains" },
  generated_by: { label: "Generated by", reverseLabel: "Generated" },
};

export const ALLOWED_RELATIONSHIPS = [
  ["rfi", "references", "drawing_sheet"],
  ["rfi", "references", "drawing_revision"],
  ["rfi", "responds_to", "drawing_revision"],
  ["rfi", "originated_from", "submittal"],
  ["rfi", "impacts", "change_order"],
  ["submittal", "references", "drawing_sheet"],
  ["submittal", "references", "drawing_revision"],
  ["submittal", "responds_to", "rfi"],
  ["submittal", "impacts", "change_order"],
  ["punch_item", "located_on", "drawing_sheet"],
  ["punch_item", "located_on", "drawing_revision"],
  ["punch_item", "impacts", "change_order"],
  ["punch_item", "resolves", "rfi"],
  ["change_order", "originated_from", "rfi"],
  ["change_order", "originated_from", "submittal"],
  ["change_order", "originated_from", "punch_item"],
  ["change_order", "references", "drawing_revision"],
  ["change_order", "impacts", "drawing_sheet"],
  ["change_order", "resolves", "rfi"],
  ["daily_log", "documents", "rfi"],
  ["daily_log", "documents", "submittal"],
  ["daily_log", "documents", "punch_item"],
  ["daily_log", "documents", "change_order"],
  ["daily_log", "references", "drawing_revision"],
  ["document", "supports", "rfi"],
  ["document", "supports", "submittal"],
  ["document", "supports", "change_order"],
  ["drawing_issue", "includes", "document"],
  ["document", "associated_with", "drawing_set"],
  ["document", "associated_with", "drawing_sheet"],
  ["document", "associated_with", "drawing_revision"],
  ["document", "associated_with", "drawing_issue"],
  ["document", "associated_with", "rfi"],
  ["document", "associated_with", "submittal"],
  ["document", "associated_with", "punch_item"],
  ["document", "associated_with", "change_order"],
  ["document", "associated_with", "daily_log"],
];

export function getRelationshipOptions(entityType) {
  const options = [];
  for (const [sourceType, relationshipType, targetType] of
    ALLOWED_RELATIONSHIPS) {
    const definition = RELATIONSHIP_DEFINITIONS[relationshipType];
    if (sourceType === entityType) {
      options.push({
        key: `${relationshipType}:outgoing:${targetType}`,
        relationshipType,
        relationshipLabel: definition.label,
        relatedType: targetType,
        direction: definition.symmetric ? "symmetric" : "outgoing",
      });
    } else if (targetType === entityType) {
      options.push({
        key: `${relationshipType}:incoming:${sourceType}`,
        relationshipType,
        relationshipLabel: definition.symmetric
          ? definition.label
          : definition.reverseLabel,
        relatedType: sourceType,
        direction: definition.symmetric ? "symmetric" : "incoming",
      });
    }
  }
  return options.sort((left, right) =>
    `${left.relationshipLabel}:${RELATIONSHIP_ENTITY_LABELS[left.relatedType]}`
      .localeCompare(
        `${right.relationshipLabel}:${RELATIONSHIP_ENTITY_LABELS[right.relatedType]}`
      )
  );
}

export function getRelationshipChoices(entityType) {
  const choices = new Map();
  for (const option of getRelationshipOptions(entityType)) {
    const choiceKey = `${option.relationshipType}:${option.direction}`;
    const choice = choices.get(choiceKey) || {
      key: choiceKey,
      relationshipType: option.relationshipType,
      relationshipLabel: option.relationshipLabel,
      direction: option.direction,
      options: [],
    };
    choice.options.push(option);
    choices.set(choiceKey, choice);
  }
  return Array.from(choices.values()).sort((left, right) =>
    left.relationshipLabel.localeCompare(right.relationshipLabel)
  );
}

export function buildRelationshipPayload(
  entityType,
  entityId,
  option,
  candidate
) {
  const current = { type: entityType, id: entityId };
  const related = { type: option.relatedType, id: candidate.id };
  const source = option.direction === "incoming" ? related : current;
  const target = option.direction === "incoming" ? current : related;
  return {
    source_type: source.type,
    source_id: source.id,
    target_type: target.type,
    target_id: target.id,
    relationship_type: option.relationshipType,
  };
}

export function isExistingRelationship(
  relationships,
  relationshipType,
  candidate
) {
  return relationships.some(
    (relationship) =>
      relationship.relationship_type === relationshipType &&
      relationship.related?.type === candidate.type &&
      relationship.related?.id === candidate.id
  );
}

export function navigateToRelationship(entity, onNavigate, projectId) {
  if (!entity?.available || !entity.route?.page || !onNavigate) return false;
  const options =
    entity.route.page === "drawingViewer"
      ? {
          sheetId: entity.route.sheet_id,
          revisionId: entity.route.revision_id,
        }
      : undefined;
  onNavigate(entity.route.page, projectId, options);
  return true;
}
